name: asp
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - nomkl
  - conda
  - ipykernel
  - nb_conda_kernels
  - s3fs
  - gcsfs
  - intake
  - intake-xarray
  - xarray
  - zarr
  - h5py
  - h5netcdf
  - matplotlib
  - libgdal
  - boto3
  - awscli
  - hvplot
  - geoviews-core
  - ipyleaflet
  - datashader
  - requests
  - pandas
  - geopandas
  - rasterio
  - rio-cogeo
  - sat-search
  - mercantile
  - contextily
  - planet
  - pip:
    - porder
    - pygeotools
    - git+https://github.com/dshean/imview.git
    - git+https://github.com/dshean/demcoreg.git
